### ISSUE TITLE
Web tv  dark mode not wroking 

### ISSUE THREAD

**Issue by iamsam404** [JioTV-Go/jiotv_go_app#16]
in Firetv DArk  mode not working when i on first time when i open app its back to normal mode can u please fix ??

**Comment by siddharthsky** [comment]
Dark mode is disabled by default, as navigation via tv remote is not visible in dark mode.

**Comment by siddharthsky** [comment]
> in Firetv DArk mode not working when i on first time when i open app its back to normal mode can u please fix ??

Update v1.1.8:  

- Added support for dark mode. [Settings > Miscellaneous >Dark Mode]
